import type { Metadata } from 'next'
import { Comfortaa } from 'next/font/google'
import './globals.css'
import { NavBar } from './_components/nav-bar/NavBar'

const inter = Comfortaa({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <NavBar/>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
